apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tf-atom-kms-alias-aws
  description: "Terraform atom: AWS KMS Alias - creates a human-readable alias for a KMS key"
  annotations:
    github.com/project-slug: PlatformStackPulse/tf-atom-kms-alias-aws
    backstage.io/techdocs-ref: dir:.
  tags: [terraform, aws, atom]
  links:
    - url: https://github.com/PlatformStackPulse/tf-atom-kms-alias-aws
      title: GitHub Repository
      icon: github
spec:
  type: terraform-module
  lifecycle: production
  owner: platform-team
  system: terraform-atoms
